### PR TITLE
Major refactor and fix #2

### LINKED ISSUE #2: Allow wait function to take timeout parameter
To be able to replace

```ruby
process.run_until(:foo) && sleep(0.1)
```

with

```ruby
process.run_until(:foo).wait(:timeout => 0.1)
```

### PR DESCRIPTION
**Pull request by pedrocarrico**
Hey @remen 
Can you please take a look?
I've refactored/moved the classes a little bit to promote a bigger separation of concerns and also added the rubocop gem to ensure a consistent coding throughout the project.
Also I've implemented the timeout on the wait function and added tests.

Next steps would be adding a travis ci build, badges, possibly a coverage report, refactor the specs a little bit...
Do you have any other ideas or feature requests?

C&C are welcomed.

Thanks for reviewing,

### CODE REVIEW

**Comment by pedrocarrico** [comment]
Hey @remen, hope you haven't forgotten about this.

**Comment by budu** [comment]
This PR looks good and is much needed!

**Comment by remen** [comment]
Wow, I am so sorry about this. Family issues and kids just made me forget all about this pull request and the gem. I'm merging now. @pedrocarrico, would you like to take over ownership of the gem? If so, how should we go about it?

**Comment by pedrocarrico** [comment]
@remen Well sure, fork_break is great and I would be glad to maintain it, I also use it on some projects of mine so it's on my best interest to keep maintaining it.
I believe you can transfer the ownership of the repo to me and I already have push rights to rubygems so we're good to go.

**Comment by remen** [comment]
When I tried to transfer ownership, it said that there already was a pedrocarrico/fork_break repository. I guess you'd have to remove that. Also, you would have to update the gemspec file to point to the correct place. Also, there are some blog posts of mine linking to this URL, but these I could of course change.

But all in all, unless you feel that it is necessary, I guess the simplest way to "take ownership" is that we let the repository live here, but you become the maintainer and are free to take the project in any direction you please.

**Comment by pedrocarrico** [comment]
Just deleted my local fork but I don't mind the option you gave. Thanks,

**Pull request merged**
